# Generated by Django 6.0.1 on 2026-01-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddcetapp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_student',
        ),
    ]
