# Generated by Django 6.0.1 on 2026-01-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcetapp1', '0002_remove_student_is_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('total_questions', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
        ),
    ]
