# Generated by Django 6.0.1 on 2026-02-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcetapp1', '0006_quizattempt_attemptanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
