# Generated by Django 6.0.1 on 2026-02-25 15:15

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcetapp1', '0008_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10 digit Indian mobile number', regex='^[6-9]\\d{9}$')])),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10 digit Indian mobile number', regex='^[6-9]\\d{9}$')]),
        ),
    ]
