# Generated by Django 6.0.1 on 2026-02-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddcetapp1', '0009_mobileotp_student_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobileOTP',
        ),
    ]
