# Generated by Django 6.0.1 on 2026-02-27 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddcetapp1', '0011_emailregistrationotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mobile',
        ),
    ]
